import Head from 'next/head';

export default function Home() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="mt-4 bg-green">
                <h1 className="w-full text-left">Hello there</h1>
            </main>
        </div>
    );
}
