import { ReactNode } from 'react';
import Header from './header/Header';

import { NextSeo } from 'next-seo';

interface PropTypes {
    children: ReactNode;
}

/**
 * MainLayout layout
 *
 * @param {NavigationProps} children
 * @returns {JSX.Element}
 */
const MainLayout = ({ children }: PropTypes): JSX.Element => {
    return (
        <>
            <NextSeo
                title="Belugasswimming Academy"
                description="Generated by create next app"
                additionalLinkTags={[
                    {
                        rel: 'icon',
                        href: '/favicon.ico'
                    }
                ]}
            />
            <Header />
            {children}
        </>
    );
};

export default MainLayout;
